#pragma once

typedef unsigned int fxState;

enum Flags {
	FX_STATE_GROUP_DESC_FLAG,
	FX_FBO_TARGET_DESC_FLAG,
	FX_FBO_BLIT_SRC_DESC_FLAG,
	FX_FBO_RES_SWAP_DESC_FLAG,
	FX_CLEARMODE_DESC_FLAG,
	FX_CLEARCOLOR_DESC_FLAG,
	FX_CLEAR_DESC_FLAG,
	FX_RENDERMODE_DESC_FLAG,
	FX_SHADER_PARAMETER_DESC_FLAG,
	FX_SHADER_DESC_FLAG,
	FX_PIPELINE_DESC_FLAG,
	FX_RESOURCE_DESC_FLAG,
};
enum fxStates {
	FX_RESOURCE_1D,
	FX_RESOURCE_2D,
	FX_RESOURCE_3D,
	FX_RESOURCE_1D_IMAGE,
	FX_RESOURCE_2D_IMAGE,
	FX_RESOURCE_3D_IMAGE,
	FX_RESOURCE_RENDERTEX,
	FX_RESOURCE_DEPTHTEX,

	FX_LINEAR,
	FX_REPEAT,
	FX_RGB32F, 
	FX_RGBA8,
	FX_RGBA16,
	FX_RGBA16F,
	FX_RGBA32F,
	FX_DEPTH_COMPONENT,
	FX_DEPTH_COMPONENT16,
	FX_DEPTH_COMPONENT24,
	FX_DEPTH_COMPONENT32,
	FX_DEPTH_COMPONENT32F,

	FX_BLEND,
	FX_BLEND_FUNC,
	FX_ALPHA_FUNC,
	FX_BLEND_FUNC_SEPARATE,
	FX_BLEND_EQUATION_SEPARATE,
	FX_LOGIC_OP,
	FX_COLOR_MASK,
	FX_BLEND_COLOR,

	//blend func and func separate parameters
	FX_ZERO,
	FX_ONE,
	FX_SRC_COLOR,
	FX_ONE_MINUS_SRC_COLOR,
	FX_DST_COLOR,
	FX_ONE_MINUS_DST_COLOR,
	FX_SRC_ALPHA,
	FX_ONE_MINUS_SRC_ALPHA,
	FX_DST_ALPHA,
	FX_ONE_MINUS_DST_ALPHA,
	FX_CONSTANT_COLOR,
	FX_ONE_MINUS_CONSTANT_COLOR,
	FX_CONSTANT_ALPHA,
	FX_ONE_MINUS_CONSTANT_ALPHA,
	FX_SRC_ALPHA_SATURATE,
	FX_SRC1_COLOR,
	FX_ONE_MINUS_SRC1_COLOR,
	FX_SRC1_ALPHA,
	FX_ONE_MINUS_SRC1_ALPHA,

	//alpha func parameters
	FX_NEVER,
	FX_LESS,
	FX_EQUAL,
	FX_LEQUAL,
	FX_GREATER,
	FX_NOTEQUAL,
	FX_GEQUAL,
	FX_ALWAYS,

	//blend equation separate
	FX_FUNC_ADD,
	FX_FUNC_SUBTRACT,
	FX_FUNC_REVERSE_SUBTRACT,
	FX_MIN,
	FX_MAX,

	//logic operations
	FX_CLEAR,
	FX_SET,
	FX_COPY,
	FX_COPY_INVERTED,
	FX_NOOP,
	FX_INVERT,
	FX_AND,
	FX_NAND,
	FX_OR,
	FX_NOR,
	FX_XOR,
	FX_EQUIV,
	FX_AND_REVERSE,
	FX_AND_INVERTED,
	FX_OR_REVERSE,
	FX_OR_INVERTED,

	//general (colormask)
	FX_TRUE,
	FX_FALSE,

	FX_TEXTURE_WRAP_S,
	FX_TEXTURE_WRAP_T,
	FX_TEXTURE_MIN_FILTER,
	FX_TEXTURE_MAG_FILTER,
	FX_TEXTURE_MAX_ANISOTROPY,
	FX_DEPTH_TEST,

	FX_DO_NOTHING,
	FX_DRAW_FULLSCREEN_QUAD,
	FX_DRAW_TRIANGLE,

	FX_COLOR_BUFFER_BIT,
	FX_DEPTH_BUFFER_BIT,
	FX_STENCIL_BUFFER_BIT,

	FX_STATE_LAST
};