#include <glew.h>
#include <SFML/Audio.hpp>
#include <SFML/Config.hpp>
#include <SFML/Graphics.hpp>
#include <SFML/Network.hpp>
#include <SFML/OpenGL.hpp>
#include <SFML/System.hpp>
#include <SFML/Window.hpp>
#include <glm/ext.hpp>
#include <map>
#include <vector>
#include <list>
#include <memory>
#include <utility>
#include <iostream>